.\" Manpage for git-tips
.TH man 1 "May 2014" "1.0" "git tips man page"
.SH NAME
git tips  \- List all unmerged branches for known remotes
.SH SYNOPSIS
git tips
.SH DESCRIPTION
List all unmerged branches for known remotes

.SH SEE ALSO
git(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Vytis Valentinavicius <xytis2000@gmail.com>
